# Spring Configuration
spring:
   application:
      name: ajax-practices-backend

   devtools:
      restart:
         enabled: true
      livereload:
         enabled: true

   mvc:
      static-path-pattern: /assets/**

   # resource handler mapping
   web:
      resources:
         static-locations: [classpath:assets/, file:/ajax-practices-uploads/]

   # servlet
   servlet:
      multipart:
         enabled: true
         max-file-size: 10485760
         max-request-size: 104857600
         file-size-threshold: 5242880

# Server Configuration
server:
   port: 8080
   servlet:
      context-path: /
   error:
      whitelabel:
         enabled: false
      path: /error